name = "itsuhima"
compatibility_date = "2024-12-01"

pages_build_output_dir = "./dist"

[env.production.vars]
API_ENDPOINT = "https://api.itsuhima.utcode.net"

[env.preview.vars]
API_ENDPOINT = ""

[vars]
API_ENDPOINT = "http://localhost:3000"