services:
  postgres:
    image: postgres:16-alpine
    container_name: itsuhima-postgres
    environment:
      POSTGRES_DB: itsuhima_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: